In [2]:
import pandas as pd

In [3]:
sd = pd.DataFrame({
    "Salary" :[1000,2000,3000,5000,7000,8000,9000,12000]
})
sd
#quartiles
median  = sd["Salary"].quantile(0.50)
q1 = sd["Salary"].quantile(0.25)
q3  = sd["Salary"].quantile(0.75)

q3

# #IQR
iqr = q3 - q1

lower_bound = q1 - (1.5 * iqr)

upper_bound = q3 + (1.5 * iqr)

upper_bound

np.float64(16500.0)

In [7]:
sd[(sd["Salary"]<lower_bound) | (sd["Salary"]>upper_bound)]

Empty DataFrame
Columns: [Salary]
Index: []

In [8]:
bd = pd.read_csv("datasets/bad_daraz_dataset.csv")
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KathMandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,KATHMANDU,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Cup,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
9,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [7]:
# # bd.isnull() #null value ma TRUE lekhxa
# bd.isnull().sum() #kati ko null xa vanera

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               1
seller              0
city                0
brand               0
gender_target       0
age                 1
reviews             0
dtype: int64

In [9]:
bd.fillna(0) #missing values ma 0 haldinxa

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KathMandu,Dell,Unisex,25,120
1,2,Phone,Electronics,0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,0.0,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,0,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,KATHMANDU,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Cup,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
9,9,Mouse,Electronics,1800,5,4.3,0,TechHub,Kathmandu,Logitech,Unisex,0,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [15]:
# dummy = pd.Series(["100","200","abc"])
# pd.to_numeric(dummy,errors="coerce")

0    100.0
1    200.0
2      NaN
dtype: float64

In [10]:
bd = pd.read_csv("datasets/bad_daraz_dataset.csv")
bd["price"] = pd.to_numeric(bd["price"], errors="coerce")
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KathMandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KATHMANDU,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Cup,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
9,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [ ]:
bd["price"]=bd["price"].fillna(bd["price"].mean())
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [24]:
bd["age"]=pd.to_numeric(bd["age"],errors="coerce")
bd["age"]=bd["age"].fillna(bd["age"].median())
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KathMandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,24.5,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,KATHMANDU,Dell,Unisex,25.0,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Cup,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
9,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,24.5,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.5,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.5,44

In [15]:
bd.dropna()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [8]:
bd.duplicated()
# bd[bd.duplicated()]

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
dtype: bool

In [17]:
bd["discountpercent"]=bd["discount_percent"].str.replace("%","")
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discountpercent
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210,15
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55,5
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30,20
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80,10
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65,NaN
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18,12
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90,5
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110,5
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12,0
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10

In [64]:
bd.duplicated("product_id")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14     True
dtype: bool

In [20]:
#bd.drop_duplicates(inplace=True) #cpmplete duplicate data lai remove plus dataset/dataframe ma changes/updates garxa
bd.drop_duplicates(subset="product_id",keep="last",inplace=True)
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
9,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12

In [9]:
bd["price"]=pd.to_numeric(bd["price"],errors="coerce")
# bd
# bd[bd["price"]<0]
# # bd[bd["rating"]>5]
# bd.loc[bd["price"]<0,"price"]=0
# bd
# bd = bd[bd["price"]>0] #kunai pani negative or extra higher biundary vanda bahira ko lagi chai remove gareara  update garxa 
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KathMandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KATHMANDU,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Cup,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
9,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [10]:
bd["city"]
# bd["city"].str.strip() #strip remove space both side ko 
#bd["city"].str.rstrip() #right side ko whitespace remove garxa
bd["city"].str.lstrip() #left  side ko whitespace remove garxa
bd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KathMandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KATHMANDU,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Cup,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
9,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [ ]:
bd["city"].str.upper() #upper case ma convert garxa
bd["city"].str.lower() #lower case ma convert garxa
bd["city"].str.title() #first character upper aru lower

0       Kathmandu
1         Pokhara
2         Itahari
3      Biratnagar
4       Kathmandu
5         Pokhara
6       Kathmandu
7          Dharan
8          Dharan
9       Kathmandu
10     Kathmandu
11     Kathmandu
12       Janakpur
13       Lalitpur
14       Lalitpur
Name: city, dtype: object